# Generated by Django 2.1.15 on 2021-02-15 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_igredient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Igredient',
            new_name='Ingredient',
        ),
    ]
